### PR TITLE
Add starship endpoint

### PR DESCRIPTION
**Pull request by DurgNomis-drol**
This adds the endpoint for starship events and launches.  https://ll.thespacedevs.com/2.0.0/swagger

I  have purposely left out some attributes to limit this rather big PR. I will add them down the line.

Example of the attribute left out:
In the event object, there should also be an object containing which programs it is associated with, but this is also part of a separate endpoint so i believe it is better to add this part when adding the other endpoint. If this does not make sense I will added (Though it will make this PR even bigger).

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Looks good, the `conftest.py` file is empty and should be removed form the PR.

**Comment by DurgNomis-drol** [comment]
No problem, i can't run pytest without it, it complains about ModuleNotFoundError. But i will remove it from the PR 😃

**Comment by ludeeus** [comment]
I know you have plans for the Home Assistant integration, I will try to publish a new version later today, so maybe it can get in before the beta is cut tomorrow.
But I can't promise anything just yet.

**Comment by DurgNomis-drol** [comment]
Awesome, no hurry 😃

**Pull request merged**
